global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    # In docker swarm, we map the service name
    static_configs:
      - targets: ['mssd_stack_backend:8080']