name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mssd-backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mssd-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mssd-backend

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Ensure pom.xml exists
      run: ls -l pom.xml
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
